services:
  erp-gamers:
    container_name: erp-gamers
    image: ghcr.io/erp-cnam/gamers:latest
    # ports:
    #   - <host>:<container>
    env_file: .env
    volumes:
      # - <host>:<container>
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - erp
    depends_on:
      - erp-connect

  erp-back:
    container_name: erp-back
    image: ghcr.io/erp-cnam/back:latest
    # ports:
    #   - <host>:<container>
    env_file: .env
    volumes:
      # - <host>:<container>
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - erp
    depends_on:
      erp-connect:
        condition: service_started
      erp-back-db:
        condition: service_healthy

  erp-money:
    container_name: erp-money
    image: ghcr.io/erp-cnam/money:latest
    # ports:
    #   - <host>:<container>
    env_file: .env
    volumes:
      # - <host>:<container>
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - erp
    depends_on:
      - erp-connect

  erp-bank:
    container_name: erp-bank
    image: ghcr.io/erp-cnam/bank:latest
    # ports:
    #   - <host>:<container>
    env_file: .env
    volumes:
      # - <host>:<container>
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - erp
    depends_on:
      - erp-connect

  erp-connect:
    container_name: erp-connect
    image: ghcr.io/erp-cnam/connect:latest
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - erp

  erp-back-db:
    container_name: erp-back-db
    image: postgres:18.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${BACK_DATABASE_USER}
      - POSTGRES_PASSWORD=${BACK_DATABASE_PASSWORD}
      - POSTGRES_DB=${BACK_DATABASE_DB}
    volumes:
      - erp-back-data:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - erp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BACK_DATABASE_USER} -d ${BACK_DATABASE_DB}"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  erp:
    name: erp

volumes:
  erp-back-data:
